//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_UsDiagnosticClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamReportTemplate
    {
        public int Id { get; set; }
        public Nullable<int> ReportCategory { get; set; }
        public string ReportWriteUps { get; set; }
        public string ReportName { get; set; }
    }
}
